export const MUSIC_RECOGNITION_SERVICE = Symbol.for('MUSIC_RECOGNITION_SERVICE');
export const REMOTE_VIDEO_EXTRACTOR_SERVICE = Symbol.for('REMOTE_VIDEO_EXTRACTOR_SERVICE');
export const YOUTUBE_VIDEO_EXTRACTOR_SERVICE = Symbol.for('YOUTUBE_VIDEO_EXTRACTOR_SERVICE');
export const SHAZAM_MUSIC_RECOGNITION_SERVICE = Symbol.for('SHAZAM_MUSIC_RECOGNITION_SERVICE');
export const APP_CONFIG_SERVICE = Symbol.for('APP_CONFIG_SERVICE');

export const MUSIC_RECOGNITION_CONTROLLER = Symbol.for('MUSIC_RECOGNITION_CONTROLLER');
export const TELEGRAM_BOT_CONTROLLER = Symbol.for('TELEGRAM_BOT_CONTROLLER');

export const METADATA_KEY = {
  telegramBot: Symbol.for('TELEGRAM_BOT_METADATA_KEY'),
  telegramBotMethodList: Symbol.for('TELEGRAM_BOT_METHOD_LIST_METADATA_KEY'),
};
