export const MUSIC_RECOGNITION_SERVICE = Symbol.for('MUSIC_RECOGNITION_SERVICE');
export const REMOTE_VIDEO_EXTRACTOR_SERVICE = Symbol.for('REMOTE_VIDEO_EXTRACTOR_SERVICE');
export const YOUTUBE_VIDEO_EXTRACTOR_SERVICE = Symbol.for('YOUTUBE_VIDEO_EXTRACTOR_SERVICE');
export const SHAZAM_MUSIC_RECOGNITION_SERVICE = Symbol.for('SHAZAM_MUSIC_RECOGNITION_SERVICE');
export const APP_CONFIG_SERVICE = Symbol.for('APP_CONFIG_SERVICE');
